### ISSUE TITLE
Log-in Issue - Stuck loading

### ISSUE THREAD

**Issue by ChaosMediaCA** [InvoiceShelf/docker#16]
After entering credentials and clicking Login the loading logo appears but never redirects to the main page. Refreshing the page takes you back to the login so you are stuck in a loop.

The expected behaviour is it takes you to the dashboard after login.

No error is displayed. Just this loading screen:
![image](https://github.com/InvoiceShelf/InvoiceShelf/assets/112575473/6d4992db-c8ed-453d-a155-3f47f2bd88c8)

Clearing cookies and trying a different browser does not work.

**Please complete the following information:**
- InvoiceShelf version:  1.1.0

**Optional info**
- OS:  Windows 10
- Browser: Chrome

**Comment by CarlSinclair** [comment]
Like I said, I already have both values in my ```.env``` file set to my InvoiceShelf subdomain. The FQDN is a completely different website but I tried setting that as well and nothing changed. I tried from a fresh browser installation to eliminate any caching possibilities. It's been weeks anyway so it definitely wouldn't be cache-related.

Is there a way to figure out what domain it is expecting or what it's authenticating against?

**Comment by gdarko** [comment]
Hey @CarlSinclair  - You can join our Discord and we can discuss more in details. Ping me in private.

**Comment by rihards-simanovics** [comment]
Stale issue

**Comment by CarlSinclair** [comment]
@gdarko I can't DM you on Discord, even though I've joined the server. I sent you a friend request.
![image](https://github.com/user-attachments/assets/00a39312-e965-4a36-b0ce-82c56f9e50d3)

**Comment by rihards-simanovics** [comment]
> @gdarko I can't DM you on Discord, even though I've joined the server. I sent you a friend request.

what's your handle on discord? I will see if something is up there.

**Comment by CarlSinclair** [comment]
> > @gdarko I can't DM you on Discord, even though I've joined the server. I sent you a friend request.
> 
> what's your handle on discord? I will see if something is up there.

carl.sinclair

**Comment by rihards-simanovics** [comment]
> > what's your handle on discord? I will see if something is up there.
> 
> carl.sinclair

you were under "extra verification" role, I have removed it, though that shouldn't affect your ability to DM Drako. You should have full access to the Discrod.

**Comment by RadosavLeovac** [comment]
To fix this issue in Chrome just go inspect / Application / Cookies and delete all cookies. That will fix the problem

**Comment by tnorchids** [comment]
I had the same issue.  I'm using NGINX Proxy Manager to proxy the site (running on port 8080 in my case) to avoid entering port numbers as part of the URL.  I updated the APP_URL, SESSION_DOMAIN, SANCTUM_STATEFUL_DOMAINS environment variables to my domain name.  Replace "foo.mydomain.net" with your host and domain name.  See below for my docker compose file.  Hope this helps someone.

services:
  invoiceshelf:
    image: invoiceshelf/invoiceshelf:latest
    container_name: invoiceshelf
    ports:
      - 8080:80
    volumes:
      - ./data:/data
      - ./conf:/conf
    networks:
      - invoiceshelf
    environment:
      - PHP_TZ=America/New_York
      - TIMEZONE=America/New_York
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=https://foo.mydomain.net
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/InvoiceShelf/database/database.sqlite # please don't touch this!
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=foo.mydomain.net
      - SANCTUM_STATEFUL_DOMAINS=foo.mydomain.net
      - STARTUP_DELAY=
      #- MAIL_DRIVER=smtp
      #- MAIL_HOST=smtp.mailtrap.io
      #- MAIL_PORT=2525
      #- MAIL_USERNAME=null
      #- MAIL_PASSWORD=null
      #- MAIL_PASSWORD_FILE=<filename>
      #- MAIL_ENCRYPTION=null
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  invoiceshelf:

**Comment by birwin88** [comment]
>  See below for my docker compose file. Hope this helps someone.


It absolutely did.  Was pulling my hair out.  Thanks

**Comment by rihards-simanovics** [comment]
> For me it was just a matter of restarting the container. But using the port directly, I didn't have a problem at all. Just with reverse proxy.

the problem is with the env vars, if it get's stuck loading then it's more likely then not an issue with one of these three env vars :

Answer copy from https://github.com/InvoiceShelf/InvoiceShelf/issues/213 issue.
---

I would like to reiterate for those who haven't read the comments above, or are still stuck.

If you're experiencing issues with CSRF, check the .env file or Docker Compose YAML for environment variables, as these determine which domains the application trusts. **NOTE**: For Docker, after changing `docker-compose.yaml`, you'll need to restart the application

```properties
APP_URL=http://192.168.1.200
APP_URL=http://192.168.1.200:8080
APP_URL=http://199.199.1.199 # not recommended, run behind reverse proxy with SSL
APP_URL=http://invoiceshelf.acme.com # not recommended, try adding SSL
APP_URL=https://invoiceshelf.acme.com
APP_URL=https://invoiceshelf.acme.com:8080
```
`APP_URL` should have:
1. protocol `http` or `https` if you are accessing it via reverse proxy with SSL, then it will be `https`, if via local IP, then `http`.
2. IP address of the server or the domain name
3. (optional) If you are using a custom port such as `:8080` or another.

```properties
SESSION_DOMAIN=invoiceshelf.acme.com:8080
```
`SESSION_DOMAIN` should have:
1. IP address of the server or the domain name
2. (optional) If you are using a custom port such as `:8080` or another.

```properties
# eg 1 - local domains only
SANCTUM_STATEFUL_DOMAINS=localhost,localhost:3000,127.0.0.1,127.0.0.1:8000,::1
# eg 2 - external domain or port
SANCTUM_STATEFUL_DOMAINS=invoiceshelf.acme.com,invoiceshelf.acme.com:8080
# eg 3 - one domain
SANCTUM_STATEFUL_DOMAINS=invoiceshelf.acme.com
```
`SANCTUM_STATEFUL_DOMAINS` should have:
1. IP address of the server or the domain name
1.1. (optional) If you are using a custom port such as `:8080` or another.
2. (optional) If you are planning to access the application from different domains, you must add a comma between each domain

**Comment by rihards-simanovics** [comment]
Locking the issue as it's very likely related to incorrect env vars setup.
